name: DevelopFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: 3.0
description: A Freedom plugin used to help others. Created by rovertpug, adroition, and PuggyCrew.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
